### ISSUE TITLE
How to refresh token

### ISSUE THREAD

**Issue by hoanghiephui** [microsoftgraph/android-java-connect-sample#13]
Please guide me how to refresh token. Thanks
I have followed instructions at the address: [https://developer.microsoft.com/en-us/graph/docs/authorization/app_authorization](https://developer.microsoft.com/en-us/graph/docs/authorization/app_authorization) But it does not work. (Error code :AADSTS70000)

**Comment by JohnMAustin78** [comment]
Hi there,
I use the public preview version of the [Microsoft Authentication Library for Android](https://github.com/AzureAD/microsoft-authentication-library-for-android). The library is designed to handle token refresh for you.  If you are not getting refreshed tokens automatically, then you can open a new issue in the MSAL Library for Android GitHub repository. 
A work around would be to disconnect the user and then connect them again.  Yes, it is suboptimal for sure! I've added a disconnect method in the AuthenticationManager class.  I suppose you can call that method when you get the stale token error from AAD.
Let me know if this helps and I will close the issue.

John Austin

**Comment by JohnMAustin78** [comment]
HoangHeiphui, I assumed that you were using the MSAL library for Android, given that you opened the issue in this repository. However, since you linked to the [Graph documentation for the REST endpoint](https://developer.microsoft.com/en-us/graph/docs/concepts/auth_v2_user#5-use-the-refresh-token-to-get-a-new-access-token), may I assume that you are writing a REST based app?  If so, then I'd like to know more about how you are requesting a new access token with the refresh token you got when first authenticated and authorized.
Can you send me a example of your REST call to get new token?

**Comment by hoanghiephui** [comment]
> Hi there,
> I use the public preview version of the [Microsoft Authentication Library for Android](https://github.com/AzureAD/microsoft-authentication-library-for-android). The library is designed to handle token refresh for you. If you are not getting refreshed tokens automatically, then you can open a new issue in the MSAL Library for Android GitHub repository.
> A work around would be to disconnect the user and then connect them again. Yes, it is suboptimal for sure! I've added a disconnect method in the AuthenticationManager class. I suppose you can call that method when you get the stale token error from AAD.
> Let me know if this helps and I will close the issue.
> 
> John Austin
